<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\modules\integrasi\models\SiasnDataUtama */

$this->title = 'Profil ASN';
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="siasn-data-utama-view">

    <div class="mb-3">
        <?= $this->render('../layout/menu.php', ['nip' => $model['nipBaru']]) ?>
    </div>

    <?= DetailView::widget([
        'template' => "<tr><th style='width:30%;'>{label}</th><td>{value}</td></tr>",
        'model' => $model,
        'attributes' => [
            'id',
            'nipBaru',
            'nipLama',
            'nama',
            'gelarDepan',
            'gelarBelakang',
            'tempatLahir',
            'tempatLahirId',
            'tglLahir',
            'agama',
            'agamaId',
            'email:email',
            'emailGov:email',
            'nik',
            'alamat',
            'noHp',
            'noTelp',
            'jenisPegawaiId',
            'jenisPegawaiNama',
            'kedudukanPnsId',
            'kedudukanPnsNama',
            'statusPegawai',
            'jenisKelamin',
            'jenisIdDokumenId',
            'jenisIdDokumenNama',
            'nomorIdDocument',
            'noSeriKarpeg',
            'tkPendidikanTerakhirId',
            'tkPendidikanTerakhir',
            'pendidikanTerakhirId',
            'pendidikanTerakhirNama',
            'tahunLulus',
            'tmtPns',
            'tglSkPns',
            'tmtCpns',
            'tglSkCpns',
            'tmtPensiun',
            'bupPensiun:integer',
            'latihanStrukturalNama',
            'instansiIndukId',
            'instansiIndukNama',
            'satuanKerjaIndukId',
            'satuanKerjaIndukNama',
            'kanregId',
            'kanregNama',
            'instansiKerjaId',
            'instansiKerjaNama',
            'instansiKerjaKodeCepat',
            'satuanKerjaKerjaId',
            'satuanKerjaKerjaNama',
            'unorId',
            'unorNama',
            'unorIndukId',
            'unorIndukNama',
            'jenisJabatanId',
            'jenisJabatan',
            'jabatanNama',
            'jabatanStrukturalId',
            'jabatanStrukturalNama',
            'jabatanFungsionalId',
            'jabatanFungsionalNama',
            'jabatanFungsionalUmumId',
            'jabatanFungsionalUmumNama',
            'tmtJabatan',
            'lokasiKerjaId',
            'lokasiKerja',
            'golRuangAwalId',
            'golRuangAwal',
            'golRuangAkhirId',
            'golRuangAkhir',
            'tmtGolAkhir',
            'nomorSptm',
            'masaKerja',
            'eselon',
            'eselonId',
            'eselonLevel',
            'tmtEselon',
            'gajiPokok',
            'kpknId',
            'kpknNama',
            'ktuaId',
            'ktuaNama',
            'taspenId',
            'taspenNama',
            'jenisKawinId',
            'statusPerkawinan',
            'statusHidup',
            'tglSuratKeteranganDokter',
            'noSuratKeteranganDokter',
            'jumlahIstriSuami:integer',
            'jumlahAnak:integer',
            'noSuratKeteranganBebasNarkoba',
            'tglSuratKeteranganBebasNarkoba',
            'skck',
            'tglSkck',
            'akteKelahiran',
            'akteMeninggal',
            'tglMeninggal',
            'noNpwp',
            'tglNpwp',
            'noAskes',
            'bpjs',
            'kodePos',
            'noSpmt',
            'tglSpmt',
            'noTaspen',
            'bahasa',
            'kppnId',
            'kppnNama',
            'pangkatAkhir',
            'tglSttpl',
            'nomorSttpl',
            'nomorSkCpns',
            'nomorSkPns',
            'jenjang',
            'jabatanAsn',
            'kartuAsn',
            'mkTahun:integer',
            'mkBulan:integer',
            'flag',
            'updated',
            'validNik',
        ],
    ]) ?>

</div>
